# Generated by Django 2.0 on 2020-03-05 05:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190901_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copywritingsettings',
            name='testimonial',
            field=wagtail.core.fields.StreamField((('row', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('datetime_reader', wagtail.core.blocks.CharBlock()), ('location_up', wagtail.core.blocks.CharBlock()), ('location_down', wagtail.core.blocks.CharBlock()), ('eventbrite', wagtail.core.blocks.URLBlock()), ('googlemap', wagtail.core.blocks.URLBlock()), ('description', wagtail.core.blocks.RichTextBlock())))),), blank=True, null=True),
        ),
    ]
