# Generated by Django 2.0 on 2020-03-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='full_bio',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='personal_image',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='position',
        ),
    ]
