# Generated by Django 2.0 on 2020-03-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200308_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
