# Generated by Django 2.0 on 2020-03-08 06:02

from django.db import migrations, models
import django.db.models.deletion
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blog', '0003_postpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='full_bio',
            field=wagtailmd.utils.MarkdownField(blank=True, verbose_name='Your personal bio'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='linkedin_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='permalink',
            field=models.URLField(blank=True, verbose_name='Full Link'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='personal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
