# Generated by Django 2.1.5 on 2020-03-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200308_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
