# Generated by Django 2.1.5 on 2020-03-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postpage_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='image_path',
            new_name='image_filename',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='personal_image',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='tags',
        ),
    ]
