# Generated by Django 2.1.5 on 2020-04-03 16:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0006_auto_20200308_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='image_filename',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='permalink',
        ),
        migrations.AddField(
            model_name='postpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='excerpt',
            field=wagtailmd.utils.MarkdownField(blank=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='Github Link'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='personal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='twitter_link',
            field=models.URLField(blank=True, verbose_name='Twitter Link'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='website',
            field=models.URLField(blank=True, verbose_name='Personal Website'),
        ),
    ]
